name: ibero_ui
description: "Librería para implementar estilos de interfaz de la Ibero."
version: 0.0.2
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  path_provider: ^2.1.4
  flutter_svg: ^2.0.10+1
  form_validation: ^3.1.1+8
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  assets:
    - assets/svg/


