name: ibero_ui
description: "Librería para implementar estilos de interfaz de la Ibero."
version: 0.0.2
homepage:

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  expandable: ^5.0.1
  path_provider: ^2.1.6
  flutter_svg: ^2.3.0
  form_validation: ^3.2.0
  permission_handler: ^13.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

  assets:
    - assets/svg/


